### PR TITLE
Add svg style support.

### PR DESCRIPTION
**Pull request by TheTekton**
Haven't written many parsers, so please excuse any naivety here. This PR uses the css parser package to set style props. When --reactNative is true, props based on react-native-svg's props.js are used to whitelist style props. Limited testing performed with a fairly complex icon set with colors in react-native.

### CODE REVIEW

**Comment by TheTekton** [comment]
Thought about building a StyleSheet for react-native, if it can work with react-native-svg. Haven't worked with svg on web much yet, but looks like <style> tags could be supported out of the box with the ReactDOM. Will try to experiment a bit more today, while I'm still thinking about this.

**Comment by TheTekton** [comment]
Quick test of web style tags didn't work out. Still likely something worth looking at, as well as using react-native StyleSheet, but don't really have a use case for either right now. I added a --color prop here which helps work with svg icons as buttons, etc.

**Review by maximalism2 — CHANGES_REQUESTED** [review]
Please, pull the the new master into your branch

**Comment by TheTekton** [comment]
Master merged.

**Comment by maximalism2** [comment]
@TheTekton After merging previous PR here is some conflict, so could you please merge master into your branch again?

**Comment by TheTekton** [comment]
@necinc master is now merged.

**Review by maximalism2 — APPROVED** [review]

**Pull request merged**
